// Code generated by internal/vmagentconfiggen DO NOT EDIT.
package main

type vmagentRemoteWriteConfig struct {
	VMAgent_aws struct {
		VMAgent_accessKey   string `json:"accessKey" yaml:"accessKey" vmagent-flag:"remoteWrite.aws.accessKey"`
		VMAgent_ec2Endpoint string `json:"ec2Endpoint" yaml:"ec2Endpoint" vmagent-flag:"remoteWrite.aws.ec2Endpoint"`
		VMAgent_region      string `json:"region" yaml:"region" vmagent-flag:"remoteWrite.aws.region"`
		VMAgent_roleARN     string `json:"roleARN" yaml:"roleARN" vmagent-flag:"remoteWrite.aws.roleARN"`
		VMAgent_secretKey   string `json:"secretKey" yaml:"secretKey" vmagent-flag:"remoteWrite.aws.secretKey"`
		VMAgent_service     string `json:"service" yaml:"service" vmagent-flag:"remoteWrite.aws.service"`
		VMAgent_stsEndpoint string `json:"stsEndpoint" yaml:"stsEndpoint" vmagent-flag:"remoteWrite.aws.stsEndpoint"`
		VMAgent_useSigv4    string `json:"useSigv4" yaml:"useSigv4" vmagent-flag:"remoteWrite.aws.useSigv4"`
	} `json:"aws" yaml:"aws"`
	VMAgent_basicAuth struct {
		VMAgent_password     string `json:"password" yaml:"password" vmagent-flag:"remoteWrite.basicAuth.password"`
		VMAgent_passwordFile string `json:"passwordFile" yaml:"passwordFile" vmagent-flag:"remoteWrite.basicAuth.passwordFile"`
		VMAgent_username     string `json:"username" yaml:"username" vmagent-flag:"remoteWrite.basicAuth.username"`
	} `json:"basicAuth" yaml:"basicAuth"`
	VMAgent_bearerToken        string `json:"bearerToken" yaml:"bearerToken" vmagent-flag:"remoteWrite.bearerToken"`
	VMAgent_bearerTokenFile    string `json:"bearerTokenFile" yaml:"bearerTokenFile" vmagent-flag:"remoteWrite.bearerTokenFile"`
	VMAgent_disableOnDiskQueue string `json:"disableOnDiskQueue" yaml:"disableOnDiskQueue" vmagent-flag:"remoteWrite.disableOnDiskQueue"`
	VMAgent_forcePromProto     string `json:"forcePromProto" yaml:"forcePromProto" vmagent-flag:"remoteWrite.forcePromProto"`
	VMAgent_forceVMProto       string `json:"forceVMProto" yaml:"forceVMProto" vmagent-flag:"remoteWrite.forceVMProto"`
	VMAgent_headers            string `json:"headers" yaml:"headers" vmagent-flag:"remoteWrite.headers"`
	VMAgent_label              string `json:"label" yaml:"label" vmagent-flag:"remoteWrite.label"`
	VMAgent_maxDiskUsagePerURL string `json:"maxDiskUsagePerURL" yaml:"maxDiskUsagePerURL" vmagent-flag:"remoteWrite.maxDiskUsagePerURL"`
	VMAgent_oauth2             struct {
		VMAgent_clientID         string `json:"clientID" yaml:"clientID" vmagent-flag:"remoteWrite.oauth2.clientID"`
		VMAgent_clientSecret     string `json:"clientSecret" yaml:"clientSecret" vmagent-flag:"remoteWrite.oauth2.clientSecret"`
		VMAgent_clientSecretFile string `json:"clientSecretFile" yaml:"clientSecretFile" vmagent-flag:"remoteWrite.oauth2.clientSecretFile"`
		VMAgent_endpointParams   string `json:"endpointParams" yaml:"endpointParams" vmagent-flag:"remoteWrite.oauth2.endpointParams"`
		VMAgent_scopes           string `json:"scopes" yaml:"scopes" vmagent-flag:"remoteWrite.oauth2.scopes"`
		VMAgent_tokenUrl         string `json:"tokenUrl" yaml:"tokenUrl" vmagent-flag:"remoteWrite.oauth2.tokenUrl"`
	} `json:"oauth2" yaml:"oauth2"`
	VMAgent_proxyURL    string `json:"proxyURL" yaml:"proxyURL" vmagent-flag:"remoteWrite.proxyURL"`
	VMAgent_rateLimit   string `json:"rateLimit" yaml:"rateLimit" vmagent-flag:"remoteWrite.rateLimit"`
	VMAgent_roundDigits string `json:"roundDigits" yaml:"roundDigits" vmagent-flag:"remoteWrite.roundDigits"`
	VMAgent_sendTimeout string `json:"sendTimeout" yaml:"sendTimeout" vmagent-flag:"remoteWrite.sendTimeout"`
	VMAgent_shardByURL  struct {
		VMAgent_ignoreLabels string `json:"ignoreLabels" yaml:"ignoreLabels" vmagent-flag:"remoteWrite.shardByURL.ignoreLabels"`
		VMAgent_labels       string `json:"labels" yaml:"labels" vmagent-flag:"remoteWrite.shardByURL.labels"`
	} `json:"shardByURL" yaml:"shardByURL"`
	VMAgent_significantFigures string `json:"significantFigures" yaml:"significantFigures" vmagent-flag:"remoteWrite.significantFigures"`
	VMAgent_streamAggr         struct {
		VMAgent_config           string `json:"config" yaml:"config" vmagent-flag:"remoteWrite.streamAggr.config"`
		VMAgent_dedupInterval    string `json:"dedupInterval" yaml:"dedupInterval" vmagent-flag:"remoteWrite.streamAggr.dedupInterval"`
		VMAgent_dropInput        string `json:"dropInput" yaml:"dropInput" vmagent-flag:"remoteWrite.streamAggr.dropInput"`
		VMAgent_dropInputLabels  string `json:"dropInputLabels" yaml:"dropInputLabels" vmagent-flag:"remoteWrite.streamAggr.dropInputLabels"`
		VMAgent_ignoreOldSamples string `json:"ignoreOldSamples" yaml:"ignoreOldSamples" vmagent-flag:"remoteWrite.streamAggr.ignoreOldSamples"`
		VMAgent_keepInput        string `json:"keepInput" yaml:"keepInput" vmagent-flag:"remoteWrite.streamAggr.keepInput"`
	} `json:"streamAggr" yaml:"streamAggr"`
	VMAgent_tlsCAFile             string `json:"tlsCAFile" yaml:"tlsCAFile" vmagent-flag:"remoteWrite.tlsCAFile"`
	VMAgent_tlsCertFile           string `json:"tlsCertFile" yaml:"tlsCertFile" vmagent-flag:"remoteWrite.tlsCertFile"`
	VMAgent_tlsHandshakeTimeout   string `json:"tlsHandshakeTimeout" yaml:"tlsHandshakeTimeout" vmagent-flag:"remoteWrite.tlsHandshakeTimeout"`
	VMAgent_tlsInsecureSkipVerify string `json:"tlsInsecureSkipVerify" yaml:"tlsInsecureSkipVerify" vmagent-flag:"remoteWrite.tlsInsecureSkipVerify"`
	VMAgent_tlsKeyFile            string `json:"tlsKeyFile" yaml:"tlsKeyFile" vmagent-flag:"remoteWrite.tlsKeyFile"`
	VMAgent_tlsServerName         string `json:"tlsServerName" yaml:"tlsServerName" vmagent-flag:"remoteWrite.tlsServerName"`
	VMAgent_url                   string `json:"url" yaml:"url" vmagent-flag:"remoteWrite.url"`
	VMAgent_urlRelabelConfig      string `json:"urlRelabelConfig" yaml:"urlRelabelConfig" vmagent-flag:"remoteWrite.urlRelabelConfig"`
}
